////   LOGIN AND REGISTRATION
export const SIGNUP_SUCCESS = 'REGISTER_SUCESS'
export const SIGNUP_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_LOADING = 'SET_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const PASSWORD_RESET = 'PASSWORD_RESET'
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED'

//// USER
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const ERROR = 'ERROR'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const PROFILE_UPDATED = 'PROFILE_UPDATED'
export const GET_USER_QUESTIONS = 'GET_USER_QUESTIONS'
export const SEARCH_USERS = 'SEARCH_USERS'

//// OTP
export const OTP_SENT = 'OTP_SENT'
export const OTP_VERIFIED = 'OTP_VERIFIED'
export const OTP_SEND_FAIL = 'OTP_SEND_FAIL'
export const OTP_VERIFY_FAIL = 'OTP_VERIFY_FAIL'

// FORUM
export const LOAD_ALL_QUESTIONS = 'LOAD_ALL_QUESTIONS'
export const GET_QUESTION = 'GET_QUESTION'
export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_ANSWER_COMMENTS = 'GET_ANSWER_COMMENTS'
export const QUESTION_ADDED = 'QUESTION_ADDED'
export const CLEAR_RESULTS = 'CLEAR_RESULTS'
export const CLEAR_QUESTION = 'CLEAR_QUESTION'
export const SEARCH_QUESTION = 'SEARCH_QUESTION'
